[workspace]
members = ["pasture-core", "pasture-io", "pasture-tools", "pasture-derive", "pasture-algorithms"]
resolver = "2"

[patch.crates-io]
# needed for emscripten fix
# https://github.com/chronotope/chrono/pull/568
chrono = { git = 'https://github.com/chronotope/chrono', branch = 'main' }

[profile.bench]
debug = true

[workspace.dependencies]
nalgebra = "0.34.1"
anyhow = "1.0.100"
bytemuck = {version = "1.23.2", features = ["derive"] }
