#version 450

// Assume positions to be 3D, sizes to be 1D

layout(local_size_x=8) in;

layout(std430, set=0, binding=0) buffer PosBuffer {
//    double positions[];
    dvec3 positions[];
};

layout(std430, set=0, binding=1) buffer SizeBuffer {
    uint sizes[];
};

void main() {
    uint n = 3;

    uint idx = gl_GlobalInvocationID.x;
    if(idx < n) {
        positions[idx].x += 1.0;
        positions[idx].y += 1.0;
        positions[idx].z += 1.0;
        sizes[idx] += 1u;
    }
}
