[package]
name = "pasture-derive"
version = "0.5.0"
authors = ["Pascal Bormann <pascal.bormann@igd.fraunhofer.de>"]
edition = "2024"
license-file = "LICENSE"
description = "Macro implementations for #[derive(PointType)]"
homepage = "https://github.com/Mortano/pasture"
repository = "https://github.com/Mortano/pasture"
keywords = ["pasture", "pointcloud", "points", "lidar"]
categories = ["data-structures"]
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
syn = { version = "3.0.3", features = ["full", "extra-traits"] }
quote = "1.0.8"
anyhow = { workspace = true }

[dev-dependencies]
pasture-core = { version = "=0.5.0", path = "../pasture-core" }
bytemuck = { version = "1.5.1" }
nalgebra = { workspace = true, features = ["convert-bytemuck"] }

[lib]
proc-macro = true
